travis:
  secure:
    BINSTAR_TOKEN: SQ6mXwAxmrwV+8cSwrNe+DtkpnJlxrOgyneyPU19hFmRAZ7kWyYLhn1LBoDhKy5/9iZofp3uqL5+E+ggtQqQZ8btwsUODbJfGuZh4Ab9WRRfH5bhOujMgAjufj7YxH5G73ji5RsWxuNpKRtExRWrGmY8EnFfZrHsgyctw5Xzyi17P1FPLf4MPC/w62YXp6ziWcwffVNG9Mxp8dgF5zYmSOFsMNnzDfX6oAXSvF7OfAZX9uCbBXOZjb9Vyt3On0hrYfhGjZ7JiKrMvCwXXyP6l7NNtxFkCmXTDU/UkO/Zw+2wx/QXDxC3vS1h6KEm4VEb4D5jYoDl1fR8KZjvUEE+92mytcG167N8kPXvzbYa7QT9MRKqRRPebnpMO6rmB8Od42qAfQIJJFuuqonng4EP0GjaB5IRHbXkqDrIIR9G0GtLfcgdxo0di95s23P7uyawM2Aan+BA6iG3TpqTn8PlhCzW6lshsY6oX6DrWW1TiuSXgvghlbV0VVfVZX1FEcHJjEVGTHNeP6JlBsPAntdZWVFkW20fC38uMB1O1WxZCvPl2h38VpLLp+Eal72sVDKyzREbGklZPedDk7nLfIry5YCEmXmcZunUzlzDOvZUAJd+G6JB3OXotETWB7OWiA1zxuf1/Fs3rTDWQWCA8F89lEWlx4muwwkaOr29VwhfEHw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
